# Generated by Django 3.2.19 on 2023-06-12 10:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="songs",
        ),
    ]
