# Generated by Django 3.2.19 on 2023-06-12 12:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_remove_album_songs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
