# Generated by Django 3.2.19 on 2023-06-08 14:53
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Song",
            new_name="Songs",
        ),
    ]
