# Generated by Django 3.2.19 on 2023-06-08 15:01
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_rename_song_songs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="songs",
            options={"verbose_name": "Song", "verbose_name_plural": "Songs"},
        ),
    ]
