# Generated by Django 3.2.19 on 2023-06-09 10:15
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("songs", "0003_alter_songs_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="songs",
            name="tags",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="songs",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        ),
    ]
