# Generated by Django 3.2.19 on 2023-06-12 07:42
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("songs", "0004_auto_20230609_1015"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Songs",
            new_name="Song",
        ),
    ]
