# Generated by Django 3.2.19 on 2023-06-12 07:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0005_rename_songs_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
