# Generated by Django 3.2.19 on 2023-06-12 10:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_remove_album_songs"),
        ("songs", "0006_auto_20230612_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="albums",
            field=models.ManyToManyField(related_name="songs", to="albums.Album"),
        ),
    ]
