# Generated by Django 3.2.19 on 2023-06-12 12:20
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("songs", "0007_song_albums"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="likes",
            field=models.ManyToManyField(
                related_name="songs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
