# Generated by Django 3.2.19 on 2023-06-12 15:12
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("songs", "0008_song_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="user",
        ),
        migrations.AddField(
            model_name="song",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="likes",
            field=models.ManyToManyField(
                related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
